name: CI

on:
  push:
    branches:
        - '!master'
  pull_request:

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    concurrency: ci-client-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install Packages
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
