name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  bun:
    name: Bun
    runs-on: ubuntu-latest
    concurrency: ci-bun-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Packages
        run: bun install

      - name: Lint
        run: bun lint:ci

      - name: Build
        run: bun run build
